
sudo: required
language: rust

rust:
    - stable

cache:
  - cargo
  - directories:
      - src/amethyst/

addons:
  apt:
    packages:
      - libasound2-dev
      - cmake

before_install:
    - gem install jekyll
    - gem install jekyll-feed
    - cargo install ghp

script:
    - ./generate.sh
    - echo "www.amethyst.rs" > build/CNAME

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    ghp build &&
    git config user.name "Travis CI Worker" &&
    git config user.email "name@example.com" &&
    git remote add deploy https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &&
    git push -fq deploy gh-pages

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d0a22aa55fe94ba11c00
        on_success: always
        on_failure: always
        on_start: never
