
sudo: required
language: rust

rust:
    - stable

branches:
  only:
    - staging
    - trying
    - master

deploy:
  local_dir: build
  fqdn: www.amethyst.rs
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

cache:
  - timeout: 360
  - cargo
  - directories:
      - amethyst

addons:
  apt:
    packages:
      - libasound2-dev
      - cmake

script:
    - ./generate.sh
