base_url = "https://amethyst.rs"
title = "Amethyst"
description = "Official website of the Amethyst game engine."
compile_sass = true
highlight_code = true
highlight_theme = "monokai"
generate_rss = true

[extra]
latest_release_tag = "v0.10.0"
author = "doomy (Alexander Lozada), Ellie Fagerberg, happens (Hilmar Wiegand) 🎺, Moxinilian (Théo Degioanni)"
website_version = "4.0"
doc_path = "/doc"
github_url = "https://github.com/amethyst/amethyst"
github_url_organization = "https://github.com/amethyst"
github_url_contribution = "https://github.com/amethyst/amethyst#contributing"
github_url_contributors = "https://github.com/amethyst/amethyst/graphs/contributors"
github_url_master_examples = "https://github.com/amethyst/amethyst/tree/master/examples"
github_url_base = "https://github.com/amethyst/amethyst"
reddit_url = "https://reddit.com/r/amethyst"
discord_invite = "https://discord.gg/amethyst"
forums_url = "https://community.amethyst-engine.org"
crates_url = "https://crates.io/crates/amethyst"

[[extra.sponsors]]
name="DigitalOcean"
image="https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/assets/SVG/DO_Logo_horizontal_blue.svg"
link="https://www.digitalocean.com/?utm_medium=opensource&utm_source=amethyst"
